name: Action Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # gomplate-version: [v3.10.0]
        gomplate-version: [v4.0.0, v3.11.8, v3.10.0]
        # os: [macos-latest, windows-latest, ubuntu-latest]
        # version: [1.1.0, 1.0.0]
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup gomplate
      uses: ./
      with:
        gomplate-version: ${{ matrix.gomplate-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify gomplate version installed
      run: |
        export GOMPLATE_VERSION=$( gomplate --version | awk '{print "v" $3}' )
        if [ "$GOMPLATE_VERSION" != "${{ matrix.gomplate-version }}" ]; then
          echo "error: gomplate version ${{ matrix.gomplate-version }} expected; got $GOMPLATE_VERSION"
          exit 1
        fi
        echo "Gomplate $GOMPLATE_VERSION installed successfully."
